import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/Header";
import { Raleway } from 'next/font/google';
import { Footer } from "./components/Footer";
import { WhatsAppButton } from "./components/WhatsAppButton";

const raleway = Raleway({
  subsets: ['latin'],
  weight: ["100", "300", "400", "700", "900"],
  display: 'swap',
  variable: '--font-raleway'
});

export const metadata: Metadata = {
  title: "Rede Baterias RealMais",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <body
        className={`${raleway.variable} antialiased relative overflow-x-hidden`}
      >
        <Header />
        {children}
        <Footer/>
        <WhatsAppButton/>
      </body>
    </html>
  );
}
